development: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: screenshots_dev
  pool: 5
  username: root
  password:

test:
  <<: *mysql
  database: screenshots_test

staging:
  <<: *mysql
  database: screenshots_production

production:
  <<: *mysql
  database: screenshots_production

